[package]
name = "touchpad-toggle"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
missing-panics-doc = "allow"
missing-errors-doc = "allow"

[profile.release]
codegen-units = 1
lto = true
